USE [xAnalytics_DW]
GO

/****** Object:  Table [dw].[TEMP_TDMA_1Dim_FlexMemberHealthCheckItem]    Script Date: 6/26/2018 11:31:37 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dw].[TEMP_TDMA_1Dim_FlexMemberHealthCheckItem](
	[C_FlexMemberHealthCheckItem_VID] [bigint] NOT NULL,
	[C_FlexMemberHealthCheckItem_FromDate] [datetime2](6) NOT NULL,
	[C_FlexMemberHealthCheckItem_ToDate] [datetime2](6) NOT NULL,
	[C_FlexMemberHealthCheckItem_OID] [bigint] NOT NULL,
	[FMHCI_FlexHealthCheckGroupId] [int] NULL,
	[FMHCI_HealthCheckItemIndex] [int] NULL,
	[FST_FlexScoreTypeId] [int] NULL,
	[FST_FlexScoreType] [varchar](50) NULL,
	[FST_IsActive] [int] NULL,
	[FST_SYS_SourceDB] [varchar](50) NULL,
	[FST_SYS_ETL_Timestamp] [datetime2](3) NULL,
	[FS_FlexScoreId] [int] NULL,
	[FS_FlexScoreValue] [int] NULL,
	[FS_ActiveDate] [datetime2](3) NULL,
	[FS_ActivatedBySystemUserId] [int] NULL,
	[FS_InactiveDate] [datetime2](3) NULL,
	[FS_InactivatedBySystemUserId] [int] NULL,
	[FS_SYS_SourceDB] [varchar](50) NULL,
	[FS_SYS_ETL_Timestamp] [datetime2](3) NULL,
	[FMHCI_DailyRotationTypeId] [int] NULL,
	[FMHCI_FullRotation] [varchar](26) NULL,
	[FMHCI_SnippetId] [int] NULL,
	[FMHCI_EducationLevel] [int] NULL,
	[FMHCI_IsActive] [int] NULL,
	[FMHCI_IsRoot] [int] NULL,
	[FMHCI_AnswerTypeVal] [int] NULL,
	[FMHCI_SYS_SourceDB] [varchar](50) NOT NULL,
	[FMHCI_SYS_ETL_Timestamp] [datetime2](3) NULL,
	[FMS_FlexMessageSetId] [int] NULL,
	[FMST_FlexMessageSetTypeId] [int] NULL,
	[FMST_FlexMessageSetType] [varchar](50) NULL,
	[FMST_FlexMessageSetTypeShort] [varchar](1) NULL,
	[FMST_IsActive] [int] NULL,
	[FMST_SYS_SourceDB] [varchar](50) NULL,
	[FMST_SYS_ETL_Timestamp] [datetime2](3) NULL,
	[FMSC_FlexMessageSetCategoryId] [int] NULL,
	[FMSC_FlexMessageSetCategoryName] [varchar](50) NULL,
	[FMSC_FlexMessageSetCategoryDescription] [varchar](150) NULL,
	[FMSC_IsActive] [int] NULL,
	[FMSC_SYS_SourceDB] [varchar](50) NULL,
	[FMSC_SYS_ETL_Timestamp] [datetime2](3) NULL,
	[FMS_FlexBiometricTypeId] [int] NULL,
	[FMS_FlexMedicationID] [int] NULL,
	[FMS_FlexMedicationSiteID] [int] NULL,
	[FMS_MBRepeatQuestionID] [int] NULL,
	[FMS_DateTimeCollectionTypeID] [int] NULL,
	[FMS_IsSystem] [int] NULL,
	[FMS_IsActive] [int] NULL,
	[FMS_AnswerResponseText] [varchar](100) NULL,
	[FMS_SYS_SourceDB] [varchar](50) NULL,
	[FMS_SYS_ETL_Timestamp] [datetime2](3) NULL,
	[FMS_Header_FlexMessageId] [int] NULL,
	[FMS_IndexItemId] [int] NULL,
	[FM_Answer_FlexMessageId] [int] NULL,
	[FM_Answer_IndexItemId] [int] NULL,
	[FMT_Answer_FlexMessageTypeId] [int] NULL,
	[FMT_Answer_FlexMessageType] [varchar](50) NULL,
	[FMT_Answer_IsActive] [int] NULL,
	[FMT_Answer_SYS_SourceDB] [varchar](50) NULL,
	[FMT_Answer_SYS_ETL_Timestamp] [datetime2](3) NULL,
	[FM_Answer_DeviceMessageId] [int] NULL,
	[FM_Answer_FlexMessageText] [varchar](1000) NULL,
	[FM_Answer_CompatibilityType] [int] NULL,
	[FM_Answer_MediaVersion] [int] NULL,
	[FM_Answer_IsSystem] [int] NULL,
	[FM_Answer_IsActive] [int] NULL,
	[FM_Answer_AnswerTextVal] [varchar](80) NULL,
	[FM_Answer_SYS_SourceDB] [varchar](50) NULL,
	[FM_Answer_SYS_ETL_Timestamp] [datetime2](3) NULL,
	[FM_Question_FlexMessageId] [int] NULL,
	[FM_Question_IndexItemId] [int] NULL,
	[FMT_Question_FlexMessageTypeId] [int] NULL,
	[FMT_Question_FlexMessageType] [varchar](50) NULL,
	[FMT_Question_IsActive] [int] NULL,
	[FMT_Question_SYS_SourceDB] [varchar](50) NULL,
	[FMT_Question_SYS_ETL_Timestamp] [datetime2](3) NULL,
	[FM_Question_DeviceMessageId] [int] NULL,
	[FM_Question_FlexMessageText] [varchar](1000) NULL,
	[FM_Question_CompatibilityType] [int] NULL,
	[FM_Question_MediaVersion] [int] NULL,
	[FM_Question_IsSystem] [int] NULL,
	[FM_Question_IsActive] [int] NULL,
	[FM_Question_AnswerTextVal] [varchar](80) NULL,
	[FM_Question_SYS_SourceDB] [varchar](50) NULL,
	[FM_Question_SYS_ETL_Timestamp] [datetime2](3) NULL,
	[FMHCI_IndexItemId] [int] NULL,
	[OBSOLETE__INDICATION] [int] NOT NULL,
	[C_FlexMemberHealthCheckItem_RUNNO_INSERT] [int] NOT NULL,
	[C_FlexMemberHealthCheckItem_RUNNO_UPDATE] [int] NOT NULL,
	[SYS_SourceDB_C_FlexMemberHealthCheckItem_VID] [varchar](75) NOT NULL,
 CONSTRAINT [PK_TEMP_TDMA_1Dim_FlexMemberHealthCheckItem] PRIMARY KEY CLUSTERED 
(
	[C_FlexMemberHealthCheckItem_VID] ASC,
	[FMHCI_SYS_SourceDB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
