USE [Analytics_DW]
GO

/****** Object:  Table [dw].[TEMP_TDMA_1Dim_Member_MemberDetail]    Script Date: 6/26/2018 11:35:48 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dw].[TEMP_TDMA_1Dim_Member_MemberDetail](
	[Member_VID] [bigint] NOT NULL,
	[Member_FromDate] [datetime2](6) NOT NULL,
	[Member_ToDate] [datetime2](6) NOT NULL,
	[Member_OID] [bigint] NOT NULL,
	[ChartId] [varchar](20) NULL,
	[Title] [varchar](10) NULL,
	[FirstName] [varchar](20) NULL,
	[MiddleName] [varchar](20) NULL,
	[LastName] [varchar](25) NULL,
	[Street] [varchar](60) NULL,
	[Street2] [varchar](60) NULL,
	[City] [varchar](30) NULL,
	[State] [varchar](2) NULL,
	[Zip] [varchar](10) NULL,
	[Email] [varchar](60) NULL,
	[DateOfBirth] [datetime2](3) NULL,
	[SSN] [varchar](12) NULL,
	[Gender] [int] NULL,
	[MaritalStatus] [int] NULL,
	[RaceId] [int] NULL,
	[LastUpdated] [datetime2](3) NULL,
	[SystemUserId] [int] NULL,
	[LockRelationshipID] [int] NULL,
	[LockTime] [datetime2](3) NULL,
	[RelatedSystemUserId] [int] NULL,
	[BusinessUnit] [varchar](50) NULL,
	[MailingSameAsHome] [int] NULL,
	[MailingStreet] [varchar](60) NULL,
	[MailingStreet2] [varchar](60) NULL,
	[MailingCity] [varchar](30) NULL,
	[MailingState] [varchar](2) NULL,
	[MailingZip] [varchar](10) NULL,
	[PassCode] [varchar](4) NULL,
	[WebUserName] [varchar](256) NULL,
	[ServiceRequestId] [varchar](20) NULL,
	[SYS_SourceDB] [varchar](50) NOT NULL,
	[SYS_ETL_Timestamp] [datetime2](3) NULL,
	[MemberId] [int] NULL,
	[Height] [numeric](4, 2) NULL,
	[FrameSize] [varchar](15) NULL,
	[ManagedGroupId] [int] NULL,
	[Occupation] [varchar](50) NULL,
	[RiskArea] [varchar](25) NULL,
	[CodeStatus] [varchar](50) NULL,
	[AdDirectives] [int] NULL,
	[DisabilityStatus] [varchar](50) NULL,
	[InsPrimaryName] [varchar](50) NULL,
	[InsPrimaryNumber] [varchar](50) NULL,
	[InsPrimaryGroup] [varchar](50) NULL,
	[InsPrimaryComment] [varchar](50) NULL,
	[InsSecondaryName] [varchar](50) NULL,
	[InsSecondaryNumber] [varchar](50) NULL,
	[InsSecondaryGroup] [varchar](50) NULL,
	[InsSecondaryComment] [varchar](50) NULL,
	[ActiveDate] [datetime2](3) NULL,
	[InactiveDate] [datetime2](3) NULL,
	[InactiveReasonId] [int] NULL,
	[TimeZoneId] [int] NULL,
	[BestTimeToCall] [int] NULL,
	[InsPrimaryEffectiveDate] [datetime2](3) NULL,
	[InsPrimaryTermDate] [datetime2](3) NULL,
	[InsSecondaryEffectiveDate] [datetime2](3) NULL,
	[InsSecondaryTermDate] [datetime2](3) NULL,
	[ProgramType] [varchar](20) NULL,
	[BillDate] [datetime2](3) NULL,
	[GoalNote] [varchar](100) NULL,
	[MemSYS_SourceDB] [varchar](50) NULL,
	[MemSYS_ETL_Timestamp] [datetime2](3) NULL,
	[Primary_LanguageId] [int] NULL,
	[Primary_LanguageText] [varchar](250) NULL,
	[Primary_SYS_SourceDB] [varchar](50) NULL,
	[Primary_SYS_ETL_Timestamp] [datetime2](3) NULL,
	[Secondary_LanguageId] [int] NULL,
	[Secondary_LanguageText] [varchar](250) NULL,
	[Secondary_SYS_SourceDB] [varchar](50) NULL,
	[Secondary_SYS_ETL_Timestamp] [datetime2](3) NULL,
	[Program] [int] NULL,
	[MonitoringPeriod] [varchar](50) NULL,
	[MonitoringDays_SYS_SourceDB] [varchar](50) NULL,
	[MonitoringDays_SYS_ETL_Timestamp] [datetime2](3) NULL,
	[OBSOLETE__INDICATION] [int] NOT NULL,
	[Member_RUNNO_INSERT] [int] NOT NULL,
	[Member_RUNNO_UPDATE] [int] NOT NULL,
	[SYS_SourceDB_Member_VID] [varchar](75) NOT NULL,
 CONSTRAINT [PK_TEMP_TDMA_1Dim_Member_MemberDetail] PRIMARY KEY CLUSTERED 
(
	[Member_VID] ASC,
	[SYS_SourceDB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
